export const GET_ID_WEATHER = 'GET_ID_WEATHER';
export const GET_LOCATION_WEATHER = 'GET_LOCATION_WEATHER';

export const SHOW_HIDE_SEARCHBAR = 'SHOW_HIDE_SEARCHBAR';
export const GET_CITIES_WEATHER = 'GET_CITIES_WEATHER';
export const CHANGE_TEMPERATURE_TYPE = 'CHANGE_TEMPERATURE_TYPE';