export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_NEXT_DAYS_WEATHER = 'GET_NEXT_DAYS_WEATHER';

export const SHOW_HIDE_SEARCHBAR = 'SHOW_HIDE_SEARCHBAR';
export const GET_CITIES_WEATHER = 'GET_CITIES_WEATHER';
export const SAVE_SEARCH_VALUE = 'SAVE_SEARCH_VALUE';

export const CHANGE_TEMPERATURE_TYPE = 'CHANGE_TEMPERATURE_TYPE';
